# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x04\x65\x63ho\"\x1b\n\x0b\x65\x63hoRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0c\x65\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\".\n\x10\x63\x61lculateRequest\x12\x0c\n\x04\x61rg1\x18\x01 \x01(\x05\x12\x0c\n\x04\x61rg2\x18\x02 \x01(\x11\"#\n\x11\x63\x61lculateResponse\x12\x0e\n\x06result\x18\x01 \x01(\x11\x32\x37\n\x04\x45\x63ho\x12/\n\x04\x63\x61ll\x12\x11.echo.echoRequest\x1a\x12.echo.echoResponse\"\x00\x32\x7f\n\tCalculate\x12\x38\n\x03sum\x12\x16.echo.calculateRequest\x1a\x17.echo.calculateResponse\"\x00\x12\x38\n\x03min\x12\x16.echo.calculateRequest\x1a\x17.echo.calculateResponse\"\x00\x42\x14Z\x12illinois/grcp/echob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\022illinois/grcp/echo'
  _globals['_ECHOREQUEST']._serialized_start=20
  _globals['_ECHOREQUEST']._serialized_end=47
  _globals['_ECHORESPONSE']._serialized_start=49
  _globals['_ECHORESPONSE']._serialized_end=80
  _globals['_CALCULATEREQUEST']._serialized_start=82
  _globals['_CALCULATEREQUEST']._serialized_end=128
  _globals['_CALCULATERESPONSE']._serialized_start=130
  _globals['_CALCULATERESPONSE']._serialized_end=165
  _globals['_ECHO']._serialized_start=167
  _globals['_ECHO']._serialized_end=222
  _globals['_CALCULATE']._serialized_start=224
  _globals['_CALCULATE']._serialized_end=351
# @@protoc_insertion_point(module_scope)
